app.config(function ($translateProvider) {
  $translateProvider.translations('fr', {
    TITLE: 'Hello',
    FOO: 'This is a paragraph.',
    BUTTON_LANG_EN: 'english',
    BUTTON_LANG_DE: 'german'
  });
  $translateProvider.translations('en', {
    TOGGLE_NAV: 'Toggle navigation',
    WELCOME: 'Welcome',
    BUILDING: 'Buildings',
    SHOPPING: 'Shopping',
    TASKS: 'Tasks',
    SCHEDULING: 'Scheduling',
    MAKETING: 'Marketing',
    TASKS_TOP_MENU: 'Tasks',
    MESSAGE_TOP_MENU: 'Messages',
    NEW_MESSAGES: 'New message(s)',
    VIEW_INBOX: 'View inbox',
    ALERT_MENU_TOP: 'Alerts',
    PROFILE: 'Profile',
    INBOX: 'Inbox',
    SETTINGS: 'Settings',
    LOG_OUT: 'Log out',
    YOU_ARE: 'You are',
    A_MAN: 'A man',
    A_WOMAN: 'A woman',
    CHOOSE_AVATAR: 'Choose an avatar',
    CHARACTER_NAME: 'Character name',
    CHARACTER_NAME_HELP: 'Your name in game',
    CHARACTER_NAME_BAD: 'The choosen name is invalid',
    TOO_SHORT: 'it must be more than {{min}} characters',
    TOO_LONG: 'it must be less than {{max}} characters',
    CREATE_CHARACTER: 'Create my character',
    COMPANY_NAME: 'Company name',
    CHOOSE_COMPANY_NAME: 'Choose the name of your company',
    COMPANY_NAME_BAD: 'The choosen name is invalid',
    INITIAL_CAPITAL: 'Initial capital',
    ALLOCATE_CAPITAL: 'Allocate a part of your capital to the company',
    BAD_NUMBER: 'The selected value is invalid, it must be a number',
    MIN_1: 'It must be greater than or equal to 1',
    OVER_CAPITAL: 'It can\'t be geater than your personal account balance (${{capital}})',
    SHARES: 'Shares',
    HOW_MANY_SHARES: 'How many shares do you want?',
    OVER_UNDREAD_CAPITAL: 'It can\'t be geater than one undread times your personal account balance ({{shares}})',
    SELECT_YOUR_ACTIVITY: 'Select your activity',
    ACTIVITY: 'Activity',
    FOOD_AND_BEVERAGE: 'Food and beverage',
    CREATE_COMPANY: 'Create company',
    LOG_IN: 'Log in',
    FORGOT_PASS: 'Forgotten password',
    REMEMBER_ME: 'Remember me',
    CNIL_STATEMENT: 'CNIL statement',
    CGU: 'Terms of use',
    SIGN_IN: 'Sign in',
    CHOOSE_ACTIVITY: 'You must choose an activity',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    TOGGLE_NAV: 'Toggle navigation',
    FOO: 'Dies ist ein Paragraph.',
    BUTTON_LANG_EN: 'englisch',
    BUTTON_LANG_DE: 'deutsch'
  });
  $translateProvider.preferredLanguage('en');
});
