app.config(function ($translateProvider) {
  $translateProvider.translations('fr', {
    TITLE: 'Hello',
    FOO: 'This is a paragraph.',
    BUTTON_LANG_EN: 'english',
    BUTTON_LANG_DE: 'german'
  });
  $translateProvider.translations('en', {
    TOGGLE_NAV: 'Toggle navigation',
    UNIVERS_HANDLING: 'Universes',
    LOG_IN: 'Log in',
    FORGOT_PASS: 'Forgotten password',
    REMEMBER_ME: 'Remember me',
    CNIL_STATEMENT: 'CNIL statement',
    CGU: 'Terms of use',
    SIGN_IN: 'Sign in',
    END_TURN: 'End Turn',
    NEW_MESSAGES: 'New message(s)',
    VIEW_INBOX: 'View inbox',
    ALERT_MENU_TOP: 'Alerts',
    PROFILE: 'Profile',
    INBOX: 'Inbox',
    SETTINGS: 'Settings',
    TASKS_TOP_MENU: 'Tasks',
    MESSAGE_TOP_MENU: 'Messages',
    LOG_OUT: 'Log out',
    ADMIN_INTERFACE: 'Admin interface',
    WELCOME: 'Welcome',
    TOO_SHORT: 'it must be more than {{min}} characters',
    TOO_LONG: 'it must be less than {{max}} characters',
    UNIVERSE_NAME_BAD: "Universe name is invalid:",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    CREATE: "Create",
    UNIVERSE_NAME : "Universe name",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
    UNIVERSE_NAME_HELP : "Choose the name of the new univers",
  });
  $translateProvider.preferredLanguage('en');
});
